source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform:ios,'8.0'
target "YXPaymentSample" do
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'YXPaymentSDK', '~> 0.0.1'
end
